### ISSUE TITLE
0 - You must specify a non-empty path to clean 

### ISSUE THREAD

**Issue by fontanil** [Valc/jmlocalise#12]
Hi,

Thanks for that new version.

I installed the 5.0.1 RC3 then replaced the files from the 6.0.1 RC1 on a local website Joomla! 5.2.0 RC3 dev and PHP 8.2

In the translation page I select administrator and french language and I get an error 0 (in the title here) for JROOT\libraries\vendor\joomla\filesystem\src\Path.php:198

I tried with German language and get "Warning: Trying to access array offset on value of type bool in D:\wamp64\www\joaktree2\administrator\components\com_localise\Model\TranslationModel.php on line 436" (and 440) but the files are listed.
In the file page: "Deprecated: Function strftime() is deprecated in D:\wamp64\www\joaktree2\libraries\src\Form\Field\CalendarField.php on line 323"

And in the package page: 0 Class "Route" not found  for JROOT\administrator\components\com_localise\tmpl\packages\default_body.php:40 

fontanil

**Comment by Valc** [comment]
[jmlocalise-6.0.1-RC1_installable.zip](https://github.com/user-attachments/files/17002799/jmlocalise-6.0.1-RC1_installable.zip)
Test fresh installable package, please.

**Comment by fontanil** [comment]
Hi Valc,

Sorry, no change. 
I had the same error a few months ago with the previous version 5, so I had to restore the Joomla! 4 version of the translation site.
I haven't found where the error occurs, and I don't understand why it only occurs in French in my tests. 

Regards,

**Comment by fontanil** [comment]
Oh no: same error on a multilingual test with all languages, frontend and backend.
Joomla! 5.1.4 PHP 8.1.29 MariaDB 10.6.19

**Comment by Valc** [comment]
Hi, fontanil
In the package that I have attached to you I have solved the error: 

> And in the package page: 0 Class "Route" not found for JROOT\administrator\components\com_localise\tmpl\packages\default_body.php:40

It failed for me too.

As for the other thing you mentioned, I can't reproduce the error.

The code on those lines tries to read the first character of each line to figure out if it is a comment or not.

> D:\wamp64\www\joaktree2\administrator\components\com_localise\Model\TranslationModel.php on line 436" (and 440) but the files are listed.

Related to that, we had a bug a while back that gave errors when trying to open blank files, but it was fixed a while ago.

Other warnings point to files that are from the Joomla core and not com_localise.

What language do you have installed in the Joomla administration, is it en-GB or one of the two that you say are failing?
If it is not en-GB, try using it in the Joomla administration.

You don't get an error with other languages?

**Comment by fontanil** [comment]
Hi Valc,

I'm using a website with en-GB + fr-FR to create translations, another with German too, and I tested on a multilingual website with English, French, German, Italian and Spanish.
On the second, I didn't have the error with German.
On the multilingual website I had an error with all languages except English. I needed each time to delete cookies for testing 
I will try on a new site.

**Comment by fontanil** [comment]
Hi Valc,

On a new J 5.1.4 en-GB website with the French language added, I won't reproduce the error. So it's an extension that I use on other sites that must have an anomaly in an original language file. I remember once having an ini file that used ‘#’ instead of ‘;’ for some comment lines. I'm going to install the extensions one by one to find out which one, and you'll see if it's possible to deal with this anomaly.

Thanks for your help!

**Comment by fontanil** [comment]
I found the reason of the error: it occurs when Localise finds a translated file but the ref file is missing, 
I'm using a modified version of JDump and I got:
 [string] ref = "/home/www/developpement/joaktree2/administrator/language/en-GB/com_jce.ini"Tooltip
[string] dest = "/home/www/developpement/joaktree2/administrator/language/fr-FR/com_jce.ini"Tooltip
[null] refTooltip
[string] dest = "/home/www/developpement/joaktree2/administrator/language/fr-FR/com_jce.menu.ini"Tooltip

"com_jce.menu.ini" seems to belong to an old version of the translated files. Same error with the old com_akeeba.ini if the old version of the translated files was not or incompletely deleted, the error will be blocking.

On new sites or site that were initilally in J4, it works, not on old J3 or earlier version where remain obsolete translation files.
I'm using Joomla! for 18 years and and a lot of websites were initially in J3 or earlier (from 1.0). ;)

I deleted a lot of old ini files, it's taken an awfully long time, and now I've got these warnings:
Warning: Trying to access array offset on value of type bool in /home/www/developpement/joaktree2/administrator/components/com_localise/Model/TranslationModel.php on line 436
But I didn't find why line[0] is boolean here.

**Comment by fontanil** [comment]
I found! ;)

On my test site, warnings are triggered by the plg_console_akeebabackup.ini and sys.ini files because they only contain comment lines. It seems to me that I've sometimes seen extensions that add a file with no translation to the frontend language files

 file = "/home/www/developpement/joaktree2/administrator/language/en-GB/plg_console_akeebabackup.ini"
ligne = FALSE

I tried to add after line 416
if(is_bool($line)) BREAK;
and I get no more warnings

Do you think this is the solution?

**Comment by Valc** [comment]
It is certainly a rare case that there are files to be translated that only contain comments and absolutely nothing to translate.
It could be checked that even if a file of that type is found, the translation in the selected language would be started.
When I have time I will check it. I have been offline for many months and I will have to get back up to date on some things.
Otherwise, I am glad that you have been solving some of the problems.

**Comment by fontanil** [comment]
Thanks Valc!

**Comment by Valc** [comment]
Now a warning message is displayed when the case happens and continue to other line.
For test purposes only
[jmlocalise-6.0.1-RC1.zip](https://github.com/user-attachments/files/17006574/jmlocalise-6.0.1-RC1.zip)
Install this package and test
From the translations view you can use the advanced filters to view only Joomla core files or third-party extensions, giving you quicker access to the problematic ones.

**Comment by fontanil** [comment]
Thanks Valc, 

But the most annoying thing remains: when the reference files no longer exist but the translated files have not been deleted (this is common on older sites), the error persists and is blocking at line 205 of TranslationModel.php

[Capture d’écran 2024-09-16 064240](https://github.com/user-attachments/assets/be89cc3d-e1a5-496c-b04e-fab73a293404)

**Comment by fontanil** [comment]
Sorry, a new error: '0 Attempt to modify property "error" on null ' saving a translation
On JROOT/administrator/components/com_localise/Model/TranslationModel.php:1705 

I changed to
						//$this->item->error[] = $lineNumber;
						Factory::getApplication()->enqueueMessage('erreur ligne : ' .$lineNumber);
to get the text of the line in the reference file, so it's easyer to solve the error

**Comment by Valc** [comment]
If the errors are changing lines, it means we are making some progress :D
[jmlocalise-6.0.1-RC1.zip](https://github.com/user-attachments/files/17010560/jmlocalise-6.0.1-RC1.zip)
Try now and if you still get errors send screenshots as you did before.

**Comment by fontanil** [comment]
With that new version, I have the error "0 Attempt to modify property "error" on null ", but if I refresh the page, the lit of files are displayed.
I open a file and save and close, I get the same error, and I don't know where the error happens and what reference file is missing.

**Comment by Valc** [comment]
Can't you find it in more detail in the server error log?
I've modified it a bit to see if I can get it to send a warning, but since I don't know exactly which line of code it fails on, it's more complicated.
[jmlocalise-6.0.1-RC1.zip](https://github.com/user-attachments/files/17012051/jmlocalise-6.0.1-RC1.zip)

**Comment by fontanil** [comment]
Error: 'Attempt to modify property "error" on null' thrown in /home/www/sitestests/admtools/administrator/components/com_localise/Model/TranslationModel.php on line 1719

As I said, I tried
//$this->item->error[] = $lineNumber;
Factory::getApplication()->enqueueMessage('error on line: ' .$lineNumber);

Si get no more error but a message (right or not?) and the file is saved, with 

For the empty path error, I think you solved it partially with your new code in line 205, but the same error appairs on
JROOT\administrator\components\com_localise\Model\TranslationModel.php:1125 

if (File::exists($refpath))

**Comment by fontanil** [comment]
On these lines, the same "if(File::exists($refpath)" displays a deprecated message
![Capture d’écran 2024-09-16 160116](https://github.com/user-attachments/assets/4200a5d3-3fa4-4df3-8f5a-5df2fe3a4380)

**Comment by Valc** [comment]
Yes, the message is right but we need to handle files with errors so the user can notice it and edit to solve and comment that code line does not allow to do it.

From "Translations view" >> "filter Options" >> "Select state = Error" will display the detected cases if present.

From "Packages" the "Extra files in translation" will display righty the cases when reference language file does not exists.

![extrafiles](https://github.com/user-attachments/assets/1899420d-96c6-4a58-b9e5-adf513790783)


IF there is a dowloable package from language files than dump errors as you have, send me the link and i will try.

The fact that a line in a file to be translated cannot be enumerated because it returns "NULL" or that the object does not start as in the rest of the cases where the reference file is also missing is what is strange.
It is possible that if the en-GB file only has comments, some errors may appear when the translation starts, but I have left source files with only the comments and no errors occur that prevent the code from working, and I cannot reproduce it.

Here just after installa Akeeba Backup
![error](https://github.com/user-attachments/assets/6a095fc2-459e-45fd-8f4e-c05b285572bb)

Explaining than the "es-ES" translation is not started due it is true in my case:
![no_translation](https://github.com/user-attachments/assets/c8b12b5c-1687-4122-b27a-8341efce26a0)

**Comment by fontanil** [comment]
Thanks! I have these errors on Translations view. I didn't try to export an package with the new version for J5.

**Comment by Valc** [comment]
Hi
The new version RC2 allow codemirror working again to parse ini files syntax,  under J5.
Now the detectable syntax errors will be visible editing the file clicking in "Source", from translations view.
![editsource](https://github.com/user-attachments/assets/68221019-0dab-4de0-9a4b-79c821b28e69)


If the mistakes are at en-GB, should be the developer of that extensión who need solve the cases, but in the meanwhile is posible from com_localise edit the source en-GB file >> Solve syntax issues at the detected lines >> save and close, and then revise translation if it was started from an en-GB file with errors.

The image display both unscaped quotes within that non core file.
![parseingerrors](https://github.com/user-attachments/assets/755b1da8-c199-4800-a627-470e1aed93a4)

**Comment by Valc** [comment]
Once the syntax errors have been resolved and before attempting to create any package, it is highly recommended to analyze the content of the files, applying the "Content issues" filter, also from the translations view: these types of content errors are not really syntax errors but they can also cause what should be displayed in that language from Joomla to fail.

![issuedstrings](https://github.com/user-attachments/assets/af936539-13fb-48e3-befc-861ece56d60c)

Within the translation editing mode you can also filter by "issued" to show all cases.
![missingplaceholders](https://github.com/user-attachments/assets/6be0c674-a7c1-4dd8-b9a9-734fd0b2bdf4)

**Comment by Valc** [comment]
Therefore, although some users do not use com_localise to create packages, it can be useful to detect those cases where there are syntax errors in the files or in the content.

**Comment by fontanil** [comment]
Thank you Valc for your work!

I'm too busy to test at the moment, but I'll do it as soon as I can.

**Comment by fontanil** [comment]
Hi,

Sorry, I still have the error message "0 3 arguments are required, 2 given" in JROOT/libraries/src/Language/Text.php:281 when I select translations-->administrator-french on a website using PHP 8.1.29

**Comment by Valc** [comment]
Hi!
That's not a com_localise error, it's an error in the content of the translation you're using, where the "placeholders" in en-GB don't match those in the translation you're using.
In the language of the site and administration, use "en-GB"

And then, from the Translations view, filter by "Select content state" = "Issued"
![frissuedcases](https://github.com/user-attachments/assets/75136f53-d271-402a-a67d-2b9c4faaff19)

And open that "Issued content" files to revise the cases: editing with "Issued" filter there will be easy to see:

![frfrissuedcontent](https://github.com/user-attachments/assets/5bdfcd8d-b81b-454d-8ac4-a98c21353c6a)

Save the translation by fixing any content errors that can make Joomla fail in the translation: placeholders, brackets, square brackets... can make Joomla crash or make it fail in what should be displayed from the translation, because it does not match the en-GB.

With the translation installed without "content issues", this error that prevents the Joomla code from working should disappear.

That is why I said above that it is highly recommended to check that the translation does not have files with syntax errors or within the content.

**Comment by Valc** [comment]
Also note that if the fr-FR translation of com_localise has "content issues", it will also cause the Joomla code to fail if you use fr-FR as your default language in the administration: with en-GB this never happens, because it is the reference language and it is adjusted to the code.
![issuescomlocalise](https://github.com/user-attachments/assets/603bd647-e9e9-4cc1-ba07-b8dae13e72d1)

**Comment by fontanil** [comment]
Sorry Valc, I defined the language to en-GB for site and administrator, but when I select administrator and english or administrator and french in the translation page, the error is the same
Si I can't know what are the files to correct.

That error doesn't occur on a J4 website.

**Comment by Valc** [comment]
Try to use last release, yesterday i fix some language files of com_localise wiith content issues.
https://github.com/Valc/jmlocalise/releases/tag/6.0.1-RC5

**Comment by fontanil** [comment]
Thanks for the new version. I will test asap.

I'm trying on a new site to translate Localise in French, but the session ended before saving, so I losed all new translations. :(
I need to start again...

**Comment by fontanil** [comment]
I made a lot of translations for Localise, but need to check them.

I installed the extension I want to verify, solved the issues then I opened a file, made change and when I save, a new error "Attempt to modify property "error" on null " on JROOT\administrator\components\com_localise\Model\TranslationModel.php:1718  but I don't get a reason for that error, so I can't solve the problem.

With two var_dump, I get the line and its strings:
int(1) string(32) "﻿; Joomla! component Joaktree " 
It's the first line of the file. Same error on the same strings in another file

**Comment by fontanil** [comment]
I restored a previous version and the last error has disappeared

**Comment by Valc** [comment]
Utch I'll have to check the "keep alive" thing so that when editing the translation is not lost because the session has expired, it seems that in Joomla 5 something must have changed, because it used to work fine.
What did you restore to the previous version?
If you could attach those files that gave you the error, I can try to see if they work for me or show me what syntax error it is.
In the worst case scenario it could be corrupted files, and copying and pasting the contents of the file into a new one usually fixes it when saving.

About that last error when preprocessing the form I have modified the code a bit because I think there was an error when calling the object to assign an error.
Install this package to test before I update it on Github.
[com_localise-6.0.1_test.zip](https://github.com/user-attachments/files/17263035/com_localise-6.0.1_test.zip)

**Comment by Valc** [comment]
Be careful, when you reinstall com_localise the translation files are also rewritten, so if you were translating fr-FR... save the content somewhere else until we update it on Github.. or you will end up having nightmares XD

**Comment by fontanil** [comment]
Yes, Valc, I had made a backup of the site before installing Joaktree to add and check previous translations.
I restored the backup and reinstalled Joaktree and a copy of the previous changes in the Joaktree ini files.
Perhaps the error "Attempt to modify property "error" on null " came from a space placed before the exclamation mark on the first line of the: " !Joomla component Joaktree" instead of "! Joomla component Joaktree"

I will try the new version, so I just created a package for Localise before updating, but the package installs the files in administrator/language/fr-FR, not in component/com_localise/language/fr-FR
How to do when extensions use their own language files and not the files in the Joomla language folders?

**Comment by Valc** [comment]
Ok, is it working for you in the end? Because the tricky thing is working with language files that contain errors that prevent the Joomla code from working properly.
The issue of maintaining the session when editing should also be fixed in the latest test package.
Third-party extension packages have these kinds of limitations, and if someone wants more customizable third-party extension packages they would have to do it by hand.
Note that the native Joomla language does not need to create any installation package, only the translations, and the same thing happens with com_localise: the com_localise translations have to be sent to our Github so that everyone who downloads the latest version has the most up-to-date translation.
With most popular third-party extensions, it's more or less the same: it's the extension author who maintains the translations sent to him by the teams that help him translate his extension, and he offers them for download in the way that seems most convenient to him, or directly to install with his extension.

**Comment by fontanil** [comment]
I use Localise only for extensions translations, often only for me, sometimes to share the files when the author does not offer its own translation.

My last translations for Localise and Joaktree were made on a new J5 site. For the moment, I didn't test the new version of Localise on the sites where I got the errors 0.

The most important problem is to know why the error occurs, and when an error 0 only show the error line, we can't find what is the concerned file and the string line that triggers the error.

**Comment by fontanil** [comment]
[fr-FR_com_localise.zip](https://github.com/user-attachments/files/17265496/fr-FR_com_localise.zip)
I hope there are no too translations errors.
Thanks to DeepL and Google Translator for their help in translating certain words and phrases.

**Comment by fontanil** [comment]
I just installed the test version on the site where I had the error and have no change: 3 arguments are required, 2 given 
I can't find the file which triggers this error

The error ih here; I added a echo to find the reason of the error

> if (!is_string($line))
         {
        Factory::getApplication()->enqueueMessage(Text::sprintf('COM_LOCALISE_FILE_LINE_IS_NOT_A_STRING',
                       $fname),
                        'warning');
                        continue;
          }

The result is "plg_console_akeebabackup.ini" for $fname and $line is empty (in the English file)
No issued files in administrator English files

If I comment the enqueue message, no more error, the list of files is displayed.
I don't understand why the $fname I found with JDump, echo or var_dump is not empty but the $fname in the enqueue message triggers an error 

Or:

>	if(!empty($line)) {
              Factory::getApplication()->enqueueMessage(Text::sprintf('COM_LOCALISE_FILE_LINE_IS_NOT_A_STRING',
                                $fname),
                                'warning');
	}

**Comment by fontanil** [comment]
For Site ->French, 
error in JROOT/administrator/components/com_localise/tmpl/translation/raw.php:94 JHTML not found

JROOT/administrator/components/com_localise/Model/TranslationModel.php:1721  Attempt to modify property "error" on array 
and if I change line 1719 to
if (!empty($linenumber) && is_numeric($lineNumber))
Warning: Undefined variable $fname in /home/www/developpement/joaktree2/administrator/components/com_localise/Model/TranslationModel.php on line 1726

The site uses PHP 8.1.29 and Joomla! 5.2.0-RC1

**Comment by Valc** [comment]
Please, first of all try to test with Joomla 5.1.4, or the last one released as "stable" from the main Joomla page.
Other releases type RC or under development can apply changes that i will need to solve later, when that code become "stable" to download from the Joomla Project. Maybe the required PHP version to J5.2 is bigger.. so, we test with the current stable software.
I will revise again, and ty for the fr-FR translation, i will upload to our Github ASAP.

**Comment by fontanil** [comment]
Joomla 5.2.0 will be published in 10 days.
No changes after the RC1, only corrections. The actual errors are independant of the Joomla! version, only PHP don't accept $fname empty.

**Comment by Valc** [comment]
$fname can not be empty due previously is revised the if file path exists.
And can not be undefined, due is clearly defined by code.
```
				if (File::exists($path))
				{
					$devpath    = LocaliseHelper::searchDevpath($gh_client, $refpath);
					$custompath = LocaliseHelper::searchCustompath($gh_client, $refpath);
                    $fname      = basename($path);
```

**Comment by Valc** [comment]
Do the CHMOD permissions on your failing language files allow reading and writing to the server?

If you can send me the GB files of that Akeeba plugin I will try them on my installation.
If in 10 days they are going to release the J5.2 version, when I update my site, we will be using exactly the same Joomla code.
Here the diff
https://github.com/joomla/joomla-cms/compare/5.1.4...5.2-dev

"3 arguments and 2 given error" is an old knowed issue than make crash Joomla due mistakes with placeholders within the translation (For this reason the com_localise code tries to detect such cases since that bug was detected in the Russian language):
https://issues.joomla.org/tracker/joomla-cms/35002

If there is a third-party extension running a translation or en-GB with that type of error or similar when accessing com_localise, exactly the same thing will happen, and when the Joomla code stops, the com_localise code stops working as well.
In order for com_localise to detect it, the language file with syntax errors or errors within the content cannot be loaded by Joomla CMS at the same time as accessing "translations" or "edit translation" views or no way.

**Comment by fontanil** [comment]
Here is the file "plg_console_akeebabackup.ini" content
;; @package   akeebabackup
;; @copyright Copyright (c)2006-2024 Akeeba Ltd / Nicholas K. Dionysopoulos
;; @license   GNU General Public License version 3, or later

**Comment by Valc** [comment]
After update to J5.2 is crashing with same error message when is used that content.
I think is solved now.
Test it before i send a new com_localise version to dowload.
Warning "The line Nº4 is not a string or its is a file without keys to translate." should be displayed.

[com_localise-6.0.1-testing_bug.zip](https://github.com/user-attachments/files/17382222/com_localise-6.0.1-testing_bug.zip)

**Comment by fontanil** [comment]
Thanks a lot, valc! 
The error is still there, but a warning indicates that the file is in error:
![Capture d’écran 2024-10-16 080401](https://github.com/user-attachments/assets/e7160c5e-71e3-4af1-9c60-02a6025b3b62)

**Comment by fontanil** [comment]
In the previous case, I filtered on administrator and French. I don't understand why the error 0 occurs only in French. I tried wit German and had no error.

Now I choose English, and the file is not set as in error, though the alert for the line 4 is there
![Capture d’écran 2024-10-16 080937](https://github.com/user-attachments/assets/13634e61-1db7-43e9-a7ff-bfe3b58fc407)
What can we do in that case?

**Comment by Valc** [comment]
It's not the same error. That's another problem to try to solve. Enable system debugging from Joomla. Make sure that the PHP memory limit is sufficient so that the "debug mode" doesn't break because of that.
If there is any reference in debug that points to files in com_localise... tell me which ones.

**Comment by Valc** [comment]
The en-GB language is the reference we have to start translations, or continue them.
It is possible that in the en-GB code of an extension the "sprintf" variables do not match those of the en-GB language file of that same extension: that was the bug fixed in the com_localise code: it seems that after so much review and modification of those same lines of code because I could not reproduce the error, I removed the "$line_number" variable from our code... without realizing that I had to put it back, or, remove the en-GB placeholder.

Once that fails in en-GB, the same problem occurs in the rest of the translations, due translations are keeping the reference: developer mistake.

If the error only persists in one of the translations, then it only occurs when that language is the default and you try to access the translation views or edit, with files that have nothing to translate... only comments, which is where the code calls the selected language string to show the warning: translation mistake due that language is not updated with last en-GB changed strings.

I don't know why some developers have empty language files or ones with only comments and nothing to translate, but since it happens from time to time, it simply warns the translator that there is nothing to translate there: if it is mandatory to have such files in the translation package, it is something that should be clarified by the developer of said extension.

**Comment by fontanil** [comment]
In the previous tests, the administrator language was English: no error in English and German, error 0 in French on JROOT\libraries\vendor\joomla\filesystem\src\Path.php:198 
![Capture d’écran 2024-10-16 095127](https://github.com/user-attachments/assets/366723d3-fae2-47ca-931a-715e76595d48)
When the error 0 occurs, I need to delete cookies, because I can't change the language in the translation page.

**Comment by fontanil** [comment]
On a 4.4.8 site migrated on 4.4.9 where the previous 5.0.1 version worked without error, I migrated to 5.2.0 and installed your last version. 
I set administrator and site language to English and tried to open the translation par for administrator and English and got that page
![Screenshot 2024-10-16 at 10-09-09 Error 500](https://github.com/user-attachments/assets/c02a51f9-adf0-4fa8-a5b5-698d26da1407)

**Comment by Valc** [comment]
Test again nwe package.
If persist on same com_localise lines of code or after this changes, let me know.
[com_localise-6.0.1-testing_bug2.zip](https://github.com/user-attachments/files/17391898/com_localise-6.0.1-testing_bug2.zip)

**Comment by fontanil** [comment]
Thank you valc!

On the same site (a lot of extensions for tests) I have now (administrator English) numerous red messages (the file is empty) then 4 "The line Nº4 is not a string or it is a file without keys to translate.".
Then a great number of "Deprecated: basename(): Passing null to parameter #1 ($path) of type string is deprecated in /home/www/sitestests/admtools/administrator/components/com_localise/Helper/LocaliseHelper.php on line 2065" for various line numbers.
The site uses Joomla! 5.2.0 on PHP 8.1.29, debug on and error reporting to maximum.

**Comment by fontanil** [comment]
I set the debug Off, the error reporting to none and changed the language to French: no more error 0

But another problem: install the last version doesn't install the French ini files for Localise but the English files on that site. And install the French pack I made some days ago succeeds but the files remains in English. On the server, the chmod is 644 for ini ans sys.ini

The French translation for COM_LOCALISE_FILE_LINE_IS_NOT_A_STRING is
[%1$s] La ligne Nº%2$s n'est pas une chaîne de caractères ou c'est un fichier sans clés à traduire.

**Comment by fontanil** [comment]
Another problem: on a plugin, the first line of the ini and sys.ini file begins with a space:
" ;UWIX" 
so Localise displays an error.

**Comment by Valc** [comment]
> Another problem: on a plugin, the first line of the ini and sys.ini file begins with a space:
> " ;UWIX"
> so Localise displays an error.

Edit in raw mode and solve the issue, then, save and close.

**Comment by Valc** [comment]
> The French translation for COM_LOCALISE_FILE_LINE_IS_NOT_A_STRING is
> [%1$s] La ligne Nº%2$s n'est pas une chaîne de caractères ou c'est un fichier sans clés à traduire.

That is ok, but ensure you use the default com_localise language files stored at the component folder and not your installable language pack of com_localise (if i understand right)
I suggest delete the ones at main language folder if you intall it with a custom com_localise language fiiles.

**Comment by Valc** [comment]
CHMOD is OK if your apache config match the user and group that the file display as "user and group".
If you can edit and save a translation, you have not CHMOD issues, as normal case.

**Comment by fontanil** [comment]
> Edit in raw mode and solve the issue, then, save and close.

Yes, but it is not the task of the Localise user to correct anomalies in an extension author's language file, especially in a space like this  that can be avoided with a trim, I think.

Otherwise, it seems to me that the translations page works almost completely well. 
A slightly awkward point: when you filter by searching for a word to select files of an extension, the first click on the magnifying glass refreshes the page without applying the filter, so you have to click a second time.

**Comment by Valc** [comment]
If the author  does not correct it, the syntax error will still be there in every download of his extension.
We also do not try to automatically remove the "extras" in translation, or cases of duplicate plurals and the like: these are things that must be manually checked by the translator.

**Comment by Valc** [comment]
> A slightly awkward point: when you filter by searching for a word to select files of an extension, the first click on the magnifying glass refreshes the page without applying the filter, so you have to click a second time.

Confirmed, here same issue, but no idea about why.. i will take a look

**Comment by fontanil** [comment]
Thanks for your work!

**Comment by Valc** [comment]
"search" issue solved and new release ready to download.
I will close the thread because it is more advisable and orderly to keep separate threads for each case to be resolved.
